### ISSUE TITLE
Not working in android level 12

### ISSUE THREAD

**Issue by SudoDios** [LSPosed/AndroidHiddenApiBypass#12]
hello.
I using HokoBlurDrawable and Using method `callDrawGLFunction2` in class `android.graphics.RecordingCanvas`.
i try to use this in api 30 to the top.

**Comment by vvb2060** [comment]
https://github.com/LSPosed/AndroidHiddenApiBypass/runs/4483441331?check_suite_focus=true Android 12 unit test passed. Please provide logs, otherwise the issue will be closed.

**Comment by yujincheng08** [comment]
Because `callDrawGLFunction2` is removed from Android 12.
https://cs.android.com/android/_/android/platform/frameworks/base/+/aa4c982294ba93266136bf10bbab67bc3f2ae273

**Comment by SudoDios** [comment]
What is alternative of this function `callDrawGLFunction2` ??
