### ISSUE TITLE
Use HiddenApiBypass.invoke() or Method.invoke()?

### ISSUE THREAD

**Issue by samlu** [LSPosed/AndroidHiddenApiBypass#13]
I noticed that version 3.0 adds a HiddenApiBypass.invoke() function.
Is the HiddenApiBypass.invoke() just a helper function, or do we have to change to use this function instead of the traditional Method.invoke() function?

What about the Field.get()?
I don't see a HiddenApiBypass.get() function provided.

**Comment by yujincheng08** [comment]
`HiddenApiBypass.invoke` is somehow more efficient because it reuses the `Method` object when searching for the matching method, and it will stop searching for the rest methods if it finds the right one.

And thanks for your suggestion; we now added hidden fields bypass.
