### ISSUE TITLE
调用@RequiresPermission的方法报错

### ISSUE THREAD

**Issue by mengxiabing** [LSPosed/AndroidHiddenApiBypass#40]
调用方法报错，提示Caused by: java.lang.SecurityException: You need MANAGE_USERS or GET_ACCOUNTS_PRIVILEGED permissions to: get user name，请问此类方法如何绕过检查系统权限。

private void getUserNameByPass() throws ClassNotFoundException, InvocationTargetException, NoSuchMethodException, IllegalAccessException {
        if (android.os.Build.VERSION.SDK_INT > 27) {
//            Object obj = org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Class.forName("dalvik.system.VMDebug"), null, "getInstancesOfClasses", new Class[]{MainActivity.class}, true);
            Class<?> cls = UserManager.class;
            Object objRet = HiddenApiBypass.invoke(cls, mUserManager, "getUserName"/*, args*/);
            Log.d(TAG, "ret = " + objRet);
            if (objRet instanceof String) {
                String userName =  (String) objRet;
                Log.d(TAG, "userName = " + userName);
            }
        }
    }

**Comment by yujincheng08** [comment]
我们绕过的是隐藏 API 无法调用，不是绕过系统权限。。。
