### ISSUE TITLE
Failed to resolve: org.lsposed.hiddenapibypass:hiddenapibypass:4.3

### ISSUE THREAD

**Issue by xiaokangwl** [LSPosed/AndroidHiddenApiBypass#45]
已配置过repositories，其它包也可以正常导入

Failed to resolve: com.github.LSPosed:AndroidHiddenApiBypass:v4.3
Show in Project Structure dialog
Show Details
Affected Modules: app
>> Ask Gemini

**Comment by vvb2060** [comment]
https://github.com/LSPosed/AndroidHiddenApiBypass/blob/24218ac5e2b3460d648e449dda3ac2a2219f9d97/README.md?plain=1#L24

**Comment by yujincheng08** [comment]
AI 各种幻觉怎么还真有人信的

**Comment by vvb2060** [comment]
你看看你的标题，再看看报错信息

**Comment by xiaokangwl** [comment]
<img width="1684" alt="截屏2024-08-04 18 19 47" src="https://github.com/user-attachments/assets/abe8faac-9aca-4ace-820b-f53642c89bcd">
<img width="910" alt="截屏2024-08-04 18 20 41" src="https://github.com/user-attachments/assets/76c157fa-ea62-4ebd-85d2-ace160d7967f">
都试过了不行的

**Comment by yujincheng08** [comment]
https://maven.aliyun.com/repository/public/org/lsposed/hiddenapibypass/hiddenapibypass/4.3/hiddenapibypass-4.3.pom

毫无问题
