### ISSUE TITLE
Google is forbidding this way ？

### ISSUE THREAD

**Issue by zhangjg0201** [LSPosed/AndroidHiddenApiBypass#9]
The code from art/runtime/java_lang_Class.cc

`
        // Check classes in the java.lang.invoke package. At the time of writing, the
        // classes of interest are MethodHandles and MethodHandles.Lookup, but this
        // is subject to change so conservatively cover the entire package.
        // NB Static initializers within java.lang.invoke are permitted and do not
        // need further stack inspection.
        ObjPtr<mirror::Class> lookup_class = GetClassRoot<mirror::MethodHandlesLookup>();
        if ((declaring_class == lookup_class || declaring_class->IsInSamePackage(lookup_class))
            && !m->IsClassInitializer()) {
          return true;
        }

`

**Comment by yujincheng08** [comment]
?

**Comment by vvb2060** [comment]
If it does not work, run the unit tests and upload the test results.
